import {
  Wallet, Landmark, CreditCard, PiggyBank, Banknote, Utensils, ShoppingCart, Car, ShoppingBag,
  Receipt, Home, Clapperboard, HeartPulse, GraduationCap, Plane, Fuel, Repeat, Sparkles, Gift,
  Ellipsis, Briefcase, Laptop, TrendingUp, Percent, RotateCcw, Tag, Coffee, Bus, Smartphone,
  Dumbbell, Baby, PawPrint, Wrench, Shirt, BookOpen, Music, Gamepad2, Pizza, Bike,
  UtensilsCrossed, CupSoda, Wine, Beer, Martini, IceCream, IceCreamCone, Cake, Croissant, Cookie,
  Candy, Apple, Carrot, Beef, Fish, Egg, Salad, Sandwich, Soup, Milk, Cherry, Grape, Popcorn,
  Wheat, Store, ShoppingBasket, Package, PackageOpen, Gem, Watch, Glasses, Footprints,
  WalletCards, Tags, Train, TrainFront, Ship, Sailboat, Truck, CarFront, CarTaxiFront, Caravan,
  ParkingCircle, Bath, PlaneTakeoff, PlaneLanding, Luggage, Backpack, Tent, Map, MapPin, Compass,
  Navigation, Anchor, House, Bed, Sofa, Lamp, Lightbulb, Plug, Zap, Droplet, Droplets, Flame,
  Wifi, Router, Tv, Monitor, Trash2, Recycle, Wind, Snowflake, Umbrella, Hammer, Drill, Cog,
  Settings, Key, Lock, Shield, ShieldCheck, Hospital, Pill, Stethoscope, Syringe, Cross,
  Activity, Bandage, Thermometer, Brain, Bone, Eye, Smile, Heart, HeartHandshake, Scissors,
  Palette, Brush, Film, Ticket, Camera, Headphones, Guitar, Piano, Drum, Dices, Puzzle, Swords,
  Music2, Radio, Podcast, Mic, PartyPopper, Trophy, Medal, Award, Crown, Star, Waves, Volleyball,
  Goal, Mountain, Trees, TreePine, Flower, Flower2, Leaf, Sprout, Sun, Moon, CloudRain, Building,
  Building2, Factory, Warehouse, School, Library, Notebook, NotebookPen, Pencil, Calculator,
  ClipboardList, FileText, Folder, Printer, Paperclip, Newspaper, Bookmark, Server, Database,
  Cloud, QrCode, Keyboard, HardDrive, BatteryCharging, Cable, DollarSign, Euro, PoundSterling,
  IndianRupee, JapaneseYen, CircleDollarSign, HandCoins, Coins, BadgeDollarSign, BadgePercent,
  ReceiptText, Bitcoin, TrendingDown, Vault, Nfc, BadgeCheck, Calendar, CalendarClock, Clock,
  AlarmClock, Hourglass, Timer, Bell, BellRing, Megaphone, Mail, MessageCircle, Send, Phone,
  Globe, Users, User, UserPlus, Contact, Dog, Cat, Bird, Rabbit, Turtle, Bug, Church, Feather,
  Sticker, Shapes, Blocks, ToyBrick, Rocket, Flag, Target, Cigarette, Construction,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  wallet: Wallet, landmark: Landmark, "credit-card": CreditCard, "piggy-bank": PiggyBank,
  banknote: Banknote, utensils: Utensils, "shopping-cart": ShoppingCart, car: Car,
  "shopping-bag": ShoppingBag, receipt: Receipt, home: Home, clapperboard: Clapperboard,
  "heart-pulse": HeartPulse, "graduation-cap": GraduationCap, plane: Plane, fuel: Fuel,
  repeat: Repeat, sparkles: Sparkles, gift: Gift, ellipsis: Ellipsis, briefcase: Briefcase,
  laptop: Laptop, "trending-up": TrendingUp, percent: Percent, "rotate-ccw": RotateCcw, tag: Tag,
  coffee: Coffee, bus: Bus, smartphone: Smartphone, dumbbell: Dumbbell, baby: Baby,
  "paw-print": PawPrint, wrench: Wrench, shirt: Shirt, "book-open": BookOpen, music: Music,
  gamepad: Gamepad2, pizza: Pizza, bike: Bike, "utensils-crossed": UtensilsCrossed,
  "cup-soda": CupSoda, wine: Wine, beer: Beer, martini: Martini, "ice-cream": IceCream,
  "ice-cream-cone": IceCreamCone, cake: Cake, croissant: Croissant, cookie: Cookie, candy: Candy,
  apple: Apple, carrot: Carrot, beef: Beef, fish: Fish, egg: Egg, salad: Salad,
  sandwich: Sandwich, soup: Soup, milk: Milk, cherry: Cherry, grape: Grape, popcorn: Popcorn,
  wheat: Wheat, store: Store, "shopping-basket": ShoppingBasket, package: Package,
  "package-open": PackageOpen, gem: Gem, watch: Watch, glasses: Glasses, footprints: Footprints,
  "wallet-cards": WalletCards, tags: Tags, train: Train, "train-front": TrainFront, ship: Ship,
  sailboat: Sailboat, truck: Truck, "car-front": CarFront, "car-taxi-front": CarTaxiFront,
  caravan: Caravan, "parking-circle": ParkingCircle, bath: Bath, "plane-takeoff": PlaneTakeoff,
  "plane-landing": PlaneLanding, luggage: Luggage, backpack: Backpack, tent: Tent, map: Map,
  "map-pin": MapPin, compass: Compass, navigation: Navigation, anchor: Anchor, house: House,
  bed: Bed, sofa: Sofa, lamp: Lamp, lightbulb: Lightbulb, plug: Plug, zap: Zap, droplet: Droplet,
  droplets: Droplets, flame: Flame, wifi: Wifi, router: Router, tv: Tv, monitor: Monitor,
  "trash-2": Trash2, recycle: Recycle, wind: Wind, snowflake: Snowflake, umbrella: Umbrella,
  hammer: Hammer, drill: Drill, cog: Cog, settings: Settings, key: Key, lock: Lock,
  shield: Shield, "shield-check": ShieldCheck, hospital: Hospital, pill: Pill,
  stethoscope: Stethoscope, syringe: Syringe, cross: Cross, activity: Activity, bandage: Bandage,
  thermometer: Thermometer, brain: Brain, bone: Bone, eye: Eye, smile: Smile, heart: Heart,
  "heart-handshake": HeartHandshake, scissors: Scissors, palette: Palette, brush: Brush,
  film: Film, ticket: Ticket, camera: Camera, headphones: Headphones, guitar: Guitar,
  piano: Piano, drum: Drum, dices: Dices, puzzle: Puzzle, swords: Swords, "music-2": Music2,
  radio: Radio, podcast: Podcast, mic: Mic, "party-popper": PartyPopper, trophy: Trophy,
  medal: Medal, award: Award, crown: Crown, star: Star, waves: Waves, volleyball: Volleyball,
  goal: Goal, mountain: Mountain, trees: Trees, "tree-pine": TreePine, flower: Flower,
  "flower-2": Flower2, leaf: Leaf, sprout: Sprout, sun: Sun, moon: Moon, "cloud-rain": CloudRain,
  building: Building, "building-2": Building2, factory: Factory, warehouse: Warehouse,
  school: School, library: Library, notebook: Notebook, "notebook-pen": NotebookPen,
  pencil: Pencil, calculator: Calculator, "clipboard-list": ClipboardList, "file-text": FileText,
  folder: Folder, printer: Printer, paperclip: Paperclip, newspaper: Newspaper,
  bookmark: Bookmark, server: Server, database: Database, cloud: Cloud, "qr-code": QrCode,
  keyboard: Keyboard, "hard-drive": HardDrive, "battery-charging": BatteryCharging, cable: Cable,
  "dollar-sign": DollarSign, euro: Euro, "pound-sterling": PoundSterling,
  "indian-rupee": IndianRupee, "japanese-yen": JapaneseYen,
  "circle-dollar-sign": CircleDollarSign, "hand-coins": HandCoins, coins: Coins,
  "badge-dollar-sign": BadgeDollarSign, "badge-percent": BadgePercent,
  "receipt-text": ReceiptText, bitcoin: Bitcoin, "trending-down": TrendingDown, vault: Vault,
  nfc: Nfc, "badge-check": BadgeCheck, calendar: Calendar, "calendar-clock": CalendarClock,
  clock: Clock, "alarm-clock": AlarmClock, hourglass: Hourglass, timer: Timer, bell: Bell,
  "bell-ring": BellRing, megaphone: Megaphone, mail: Mail, "message-circle": MessageCircle,
  send: Send, phone: Phone, globe: Globe, users: Users, user: User, "user-plus": UserPlus,
  contact: Contact, dog: Dog, cat: Cat, bird: Bird, rabbit: Rabbit, turtle: Turtle, bug: Bug,
  church: Church, feather: Feather, sticker: Sticker, shapes: Shapes, blocks: Blocks,
  "toy-brick": ToyBrick, rocket: Rocket, flag: Flag, target: Target, cigarette: Cigarette,
  construction: Construction,
};

/** All selectable icons (for the category/account icon picker). */
export const ICON_NAMES = Object.keys(map);

export function getIcon(name?: string | null): LucideIcon {
  if (!name) return Tag;
  return map[name] ?? Tag;
}
